/*
 * CATALOGUE DE DÉMONSTRATION
 * --------------------------
 * Ce fichier est le seul à modifier lorsque Marine Corail fournira les fiches
 * techniques, références, contenances, prix et disponibilités. Les valeurs
 * `price: null` empêchent l'affichage d'un faux total. Les caractéristiques
 * marquées `toValidate: true` ne doivent pas être considérées comme le stock
 * réel du magasin.
 */
window.MARINE_CATALOGUE = [
  {
    id: "international-micron-extra-eu",
    family: "antifouling",
    brand: "International",
    name: "Micron Extra EU",
    reference: "À renseigner",
    description: "Antifouling érodable multi-saisons pour zones à fortes salissures.",
    matrix: "erodable",
    supports: ["polyester", "bois", "acier", "plomb"],
    maxSpeed: 25,
    coverage: 9,
    coats: 2,
    packs: [0.75, 2.5, 5],
    unit: "L",
    price: null,
    thinner: "International n° 3",
    color: "#087d9f",
    toValidate: true
  },
  {
    id: "international-cruiser-uno-eu",
    family: "antifouling",
    brand: "International",
    name: "Cruiser Uno EU",
    reference: "À renseigner",
    description: "Solution érodable pour voiliers et bateaux à moteur modérés.",
    matrix: "erodable",
    supports: ["polyester", "bois", "acier", "plomb"],
    maxSpeed: 25,
    coverage: 9,
    coats: 2,
    packs: [0.75, 2.5],
    unit: "L",
    price: null,
    thinner: "International n° 3",
    color: "#138aa5",
    toValidate: true
  },
  {
    id: "international-trilux-33",
    family: "antifouling",
    brand: "International",
    name: "Trilux 33",
    reference: "À renseigner",
    description: "Antifouling semi-érodable compatible avec l’aluminium, adapté aux zones sollicitées.",
    matrix: "semi-hard",
    supports: ["polyester", "bois", "acier", "aluminium", "plomb"],
    maxSpeed: 30,
    coverage: 8.3,
    coats: 2,
    packs: [0.75, 2.5],
    unit: "L",
    price: null,
    thinner: "International n° 3",
    color: "#00a0b5",
    toValidate: true
  },
  {
    id: "international-ultra-eu",
    family: "antifouling",
    brand: "International",
    name: "Ultra EU",
    reference: "À renseigner",
    description: "Matrice dure pour bateaux rapides et zones à fortes salissures.",
    matrix: "hard",
    supports: ["polyester", "bois", "acier", "plomb"],
    maxSpeed: 99,
    coverage: 9,
    coats: 2,
    packs: [0.75, 2.5, 5],
    unit: "L",
    price: null,
    thinner: "International n° 3",
    color: "#117ca1",
    toValidate: true
  },
  {
    id: "nautix-a4-formula-plus",
    family: "antifouling",
    brand: "Nautix",
    name: "A4 Formula+",
    reference: "À renseigner",
    description: "Matrice dure haute performance pour voiliers, vedettes rapides et bateaux à l’échouage.",
    matrix: "hard",
    supports: ["polyester", "bois", "acier"],
    maxSpeed: 99,
    coverage: 10,
    coats: 2,
    packs: [2.5, 5, 20],
    unit: "L",
    price: null,
    thinner: "Nautix DA",
    color: "#ee5a3d",
    toValidate: true
  },
  {
    id: "international-toplac",
    family: "paint",
    brand: "International",
    name: "Toplac",
    reference: "À renseigner",
    description: "Laque monocomposant brillante pour les zones émergées.",
    zones: ["topsides", "interior"],
    systems: ["one-pack"],
    finishes: ["gloss"],
    supports: ["polyester", "bois", "acier", "aluminium"],
    coverage: 12,
    coats: 2,
    packs: [0.75, 2.5],
    unit: "L",
    price: null,
    thinner: "International n° 1",
    color: "#e94d3c",
    toValidate: true
  },
  {
    id: "international-perfection",
    family: "paint",
    brand: "International",
    name: "Perfection",
    reference: "À renseigner",
    description: "Finition polyuréthane bi-composant à haute résistance et brillant durable.",
    zones: ["topsides"],
    systems: ["two-pack"],
    finishes: ["gloss"],
    supports: ["polyester", "bois", "acier", "aluminium"],
    coverage: 12,
    coats: 2,
    packs: [0.75, 2.25],
    unit: "L",
    price: null,
    thinner: "International n° 9",
    color: "#d53c32",
    toValidate: true
  },
  {
    id: "international-interdeck",
    family: "paint",
    brand: "International",
    name: "Interdeck",
    reference: "À renseigner",
    description: "Peinture antidérapante peu brillante conçue pour les ponts.",
    zones: ["deck"],
    systems: ["one-pack"],
    finishes: ["non-slip", "satin"],
    supports: ["polyester", "bois", "acier", "aluminium"],
    coverage: 9.5,
    coats: 2,
    packs: [0.75, 2.5],
    unit: "L",
    price: null,
    thinner: "International n° 1",
    color: "#e34a47",
    toValidate: true
  },
  {
    id: "international-danboline",
    family: "paint",
    brand: "International",
    name: "Danboline",
    reference: "À renseigner",
    description: "Revêtement monocomposant résistant pour cales, coffres et cloisons.",
    zones: ["bilge", "interior"],
    systems: ["one-pack"],
    finishes: ["satin"],
    supports: ["polyester", "bois", "acier", "aluminium"],
    coverage: 11,
    coats: 2,
    packs: [0.75, 2.5],
    unit: "L",
    price: null,
    thinner: "International n° 1",
    color: "#4d8292",
    toValidate: true
  },
  {
    id: "international-interprotect",
    family: "paint",
    brand: "International",
    name: "Interprotect",
    reference: "À renseigner",
    description: "Primaire époxydique bi-composant à séchage rapide et protection anticorrosion.",
    zones: ["primer"],
    systems: ["two-pack"],
    finishes: ["primer"],
    supports: ["polyester", "bois", "acier", "aluminium"],
    coverage: 8.1,
    coats: 3,
    packs: [0.75, 2.5, 5],
    unit: "L",
    price: null,
    thinner: "International n° 7",
    color: "#82ad94",
    toValidate: true
  },
  {
    id: "epiglass-epoxy-marine",
    family: "resin",
    brand: "Epiglass",
    name: "Système époxy marine",
    reference: "À renseigner",
    description: "Système époxy pour stratification, collage et protection en milieu marin.",
    applications: ["lamination", "coating", "repair"],
    supports: ["polyester", "bois", "acier", "aluminium"],
    density: 1.1,
    coverage: 0,
    coats: 1,
    packs: [0.75, 3, 6],
    unit: "kg",
    price: null,
    thinner: "Ne pas diluer sans fiche technique",
    color: "#e2aa22",
    toValidate: true
  },
  {
    id: "soloplast-epoxy-inclusion",
    family: "resin",
    brand: "Soloplast",
    name: "Résine époxy inclusion",
    reference: "À renseigner",
    description: "Résine transparente destinée aux coulées et inclusions décoratives.",
    applications: ["casting"],
    supports: ["bois", "polyester"],
    density: 1.1,
    coverage: 0,
    coats: 1,
    packs: [0.75, 1, 5],
    unit: "kg",
    price: null,
    thinner: "Selon fiche technique",
    color: "#d7a531",
    toValidate: true
  },
  {
    id: "soloplast-gelcoat-finition",
    family: "resin",
    brand: "Soloplast",
    name: "Gelcoat de finition blanc",
    reference: "PRA209 — à confirmer",
    description: "Gelcoat polyester paraffiné pour réparer les éclats et obtenir une finition étanche.",
    applications: ["gelcoat", "repair"],
    supports: ["polyester"],
    density: 1.2,
    coverage: 0,
    coats: 1,
    packs: [1],
    unit: "kg",
    price: null,
    thinner: "Catalyseur selon fiche technique",
    color: "#39a8a8",
    toValidate: true
  }
];
